//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.27 at 01:59:37 PM CEST 
//


package fr.treeptik.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="concessionnaire" type="{}concessionnaire"/>
 *         &lt;element name="vehicule" type="{}vehicule" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "concessionnaire",
    "vehicule"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(required = true)
    protected Concessionnaire concessionnaire;
    @XmlElement(required = true)
    protected List<Vehicule> vehicule;

    /**
     * Gets the value of the concessionnaire property.
     * 
     * @return
     *     possible object is
     *     {@link Concessionnaire }
     *     
     */
    public Concessionnaire getConcessionnaire() {
        return concessionnaire;
    }

    /**
     * Sets the value of the concessionnaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link Concessionnaire }
     *     
     */
    public void setConcessionnaire(Concessionnaire value) {
        this.concessionnaire = value;
    }

    /**
     * Gets the value of the vehicule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Vehicule }
     * 
     * 
     */
    public List<Vehicule> getVehicule() {
        if (vehicule == null) {
            vehicule = new ArrayList<Vehicule>();
        }
        return this.vehicule;
    }

}
